#!/bin/bash
# simple backup utility using rsync

DEST=$1
[ -n $1 ] && \
rsync -aAXv --delete --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*",\
"/mnt/*","/media/*","/lost+found"} / $DEST || echo "please provide a destination"
