#!/bin/bash
# simple backup utility using rsync

rsync --info=progress2 -aAXHvv --delete \
    --exclude="/dev/*" \
    --exclude="/proc/*" \
    --exclude="/sys/*" \
    --exclude="/tmp/*" \
    --exclude="/run/*" \
    --exclude="/mnt/*" \
    --exclude="/media/*" \
    --exclude="/lost+found" \
    --exclude="/var/lib/dhcpcd/*" \
    --exclude="/var/cache/pacman/pkg/*" \
    --exclude=".cache" \
    / "$1"
