#!/bin/bash

function audio() {
    [ $(pulsemixer --get-mute) -eq 0 ] && pulsemixer --get-volume || echo "muted"
}

function main() {
    while true; do
        up=$(uptime | grep -Eo 'up *[0-9]{,2}:*[0-9]{,2}( min)*')
        date=$(date +"%H:%M, %a %d-%m-%y")
        disk=$(df -h /dev/sda2 | awk '/dev/ {print $5}')
        bat=$(acpi -b | grep -Eo '[0-9]{,3}%' | tail -n 1)
        mem=$(free | awk '/Mem/ {printf "%d%%\n", ($3 / $2)*100}')
        cpu=$(top -bn1 | awk '/Cpu\(s\)/ {print $2 + $6 "%/" $4 "%"}')
        audio=$(audio)
        ssid=$(wpa_cli status | grep -i '^ssid')

        name='                    '
        name+="  $disk |  ${audio% *} | $date |  ${up#up } |  $cpu |  $mem |"
        name+="  ${ssid#*=} |  $bat "

        xsetroot -name "$name"
        sleep 1
    done
}

case "$1" in
    "-r") barid=$(pgrep bar | sed '1q') && kill -15 $barid;
esac

main
