#!/bin/sh

PATH_TO_T="$HOME/repos/t/t.py"
TASK_DIR="$HOME/docs/tasks"
TASKS_LIST='tasks'

alias t="python $PATH_TO_T --task-dir $TASK_DIR --list $TASKS_LIST"

choice=$( echo -e "Show\nAdd\nDelete\n" | dmenu_col -i -p "Choose an action" )

[ $? -eq 1 ] && exit 0

if (test $choice = 'Add')
then
    echo "" | dmenu_col -p "TODO:"| xargs t > /dev/null
elif (test $choice = 'Delete')
then
    t | dmenu_col -p "DONE:" -i -l 10 | cut -d' ' -f1 | xargs t -f
elif (test $choice = 'Show')
then
    t | dmenu_col -p "PENDING:" -l 10 > /dev/null ; exit 0
else
    exit 0
fi
