#!/bin/sh
# Manage TODO's with https://github.com/sjl/t and dmenu

PATH_TO_T="$HOME/repos/t/t.py"
TASK_DIR="$HOME/docs/tasks"
TASKS_LIST='tasks'

# Uncomment this to use builtin dmenu
screenw=1920
screenh=1080
width=$((screenw/2))
x=$((screenw/2))
y=$((screenh/2))

alias dmenu="dmenu -x $x -y $y -z $width"
alias t="python $PATH_TO_T --task-dir $TASK_DIR --list $TASKS_LIST"

choice=$( echo -e "Show\nAdd\nDelete\n" | dmenu -i -p "Choose an action" )

[ $? -eq 1 ] && exit 0

if (test $choice = 'Add')
then
    echo "" | dmenu -p "TODO:"| xargs -0 t | xargs -0 notify-send -u low -t 1000
elif (test $choice = 'Delete')
then
    t | dmenu -p "DONE:" -i -l 10 | cut -d' ' -f1 | xargs t -f | xargs -0 notify-send -u low -t 1000
elif (test $choice = 'Show')
then
    t | dmenu -p "PENDING:" -l 10 > /dev/null ; exit 0
else
    exit 0
fi
