#!/bin/sh

screenw=1920
screenh=1080
width=$((screenw/4))
x=$((screenw/2))
y=$((screenh/2))

[ $(echo -e "No\nYes" | dmenu -p "$1" -z $width -x $x -y $y) = "Yes" ] \
    && $2 || notify-send -t 3000 "command not executed: $2"
